@base_url = http://localhost:5000/ticket
@ticketId = b4b69df7-f852-4318-bc3d-1437ee5dddea
@writeUId = b4b69df7-f852-4318-bc3d-1437ee5dddea

### Create Ticket
POST {{base_url}}?writeUId={{writeUId}}&ticketId={{ticketId}}&requirement="I HAVE PROBLEMS WITH"