version: '3.8'

services:
  api:
    build: .
    entrypoint: gunicorn --bind 0.0.0.0:5000 wsgi:app
    volumes:
      - ./src/:/home/app/src/
      - ./tests/:/home/app/tests/
    ports:
      - "${APP_PORT:-5000}:${APP_PORT:-5000}"
    env_file:
      - ./.env
    networks:
      - public

networks:
  public:
    external: true
