version: '3.8'

services:
  api:
    build: ./docker
    entrypoint: gunicorn --bind 0.0.0.0:5000 wsgi:app
    volumes:
      - ./src/:/home/app/src/
      - ./tests/:/home/app/tests/
    ports:
      - 5000:5000
    env_file:
      - ./.env