#!/usr/bin/env bash
# Load variables from .env file
source .env

# Functions
hello() {
    curl -X GET "$URL/hello"
}

getTask() {
    curl -X GET "$URL/task?writeUId=$1"
}

getTaskById() {
    curl -X GET "$URL/task/$1?writeUId=$1"
}

deleteTask() {
    curl -X DELETE "$URL/task/$1?writeUId=$1"
}

createTask() {
    uuid=$1
    curl -X POST "$URL/task" \
        --header 'Content-Type: application/json' \
        --header 'Accept: application/json' \
        -d '{
            "writeUId":"'"$uuid"'",
            "taskId":"'"$uuid"'",
            "requirement":"I HAVE PROBLEMS WITH MY PC",
            "milestones": [
                "Check the hardware",
                "Restart the PC"
            ],
            "because": "I cannot work",
            "state": 0,
            "channelType": 0
        }'
}

updateTask() {
    curl -X PUT "$URL/task/$1" \
        --header 'Content-Type: application/json' \
        --header 'Accept: application/json' \
        -d '{
            "writeUId":"'"$1"'",
            "state": 1
        }'
}

# Variables
URL="http://localhost:${APP_PORT}"
UUID='be3fbe96-1fa2-4466-8077-da9110956f85'

# Testing all functions
echo "Testing hello()"
hello

echo "Testing createTask()"
createTask "$UUID"

echo "Testing getTask()"
getTask "$UUID"

echo "Testing updateTask()"
updateTask "$UUID"

echo "Testing getTaskById()"
getTaskById "$UUID"

echo "Testing deleteTask()"
deleteTask "$UUID"
