#!/usr/bin/env bash
# Load variables from .env file
source .env

# Functions
listServices() {
    echo "Listing all available services:"
    grpcurl -plaintext "$URL" list
}

hello() {
    echo "Testing Greeter/SayHello with name='world':"
    grpcurl -plaintext -d '{"name": "world"}' "$URL" Greeter/SayHello
}

helloDescribe() {
    echo "Describing the Greeter service:"
    grpcurl -plaintext "$URL" describe Greeter
}

# Variables
URL="localhost:${RPC_PORT}"

# Testing all functions
listServices
hello
helloDescribe

